#!/bin/sh

# LEDE Firmware Config

# luci language
#uci set luci.main.lang=zh_cn
#uci commit luci

# system
uci batch <<EOF
set system.@system[0].hostname='Youku_YK-L1'
delete system.ntp.enable_server
add_list system.ntp.server="cn.ntp.org.cn"
add_list system.ntp.server="edu.ntp.org.cn"
add_list system.ntp.server="ntp.ntsc.ac.cn"
add_list system.ntp.server="ntp.tuna.tsinghua.edu.cn"
set system.ntp.use_dhcp='0'
EOF
uci commit system

# turboacc bbr_cca is on
uci set turboacc.config.bbr_cca='1'
uci commit turboacc

# fix distfeeds
sed -i "/ace8/d" /etc/opkg/distfeeds.conf
sed -i "/passwall_packages/d" /etc/opkg/distfeeds.conf
sed -i "/passwall2/d" /etc/opkg/distfeeds.conf
sed -i "/passwall/d" /etc/opkg/distfeeds.conf
sed -i "/small/d" /etc/opkg/distfeeds.conf

# firewall
uci batch <<EOF
delete firewall.@defaults[0].syn_flood='0'
set firewall.@defaults[0].input='ACCEPT'
set firewall.@defaults[0].forward='ACCEPT'
set firewall.@defaults[0].fullcone6='1'
delete firewall.@zone[0].network
add_list firewall.@zone[0].network='lan'
add_list firewall.@zone[0].network='lan6'
EOF
uci commit firewall
/etc/init.d/firewall restart

# dnsmasq
uci batch <<EOF
delete dhcp.@dnsmasq[0].boguspriv
delete dhcp.@dnsmasq[0].filterwin2k
delete dhcp.@dnsmasq[0].authoritative
delete dhcp.@dnsmasq[0].readethers
delete dhcp.@dnsmasq[0].resolvfile
set dhcp.@dnsmasq[0].domainneeded='1'
set dhcp.@dnsmasq[0].nonegcache='1'
set dhcp.@dnsmasq[0].cachesize='10000'
set dhcp.@dnsmasq[0].filter_aaaa='1'
set dhcp.@dnsmasq[0].noresolv='1'
set dhcp.@dnsmasq[0].nohosts='1'
set dhcp.@dnsmasq[0].server='1.1.1.1#443'
delete dhcp.lan.start
delete dhcp.lan.limit
delete dhcp.lan.leasetime
delete dhcp.lan.dhcpv6
delete dhcp.lan.ra
set dhcp.lan.ignore='1'
set dhcp.lan.dns='::1'
EOF
uci commit dhcp
/etc/init.d/dnsmasq restart

# network config
uci batch <<EOF
delete network.lan.ip6assign
delete network.globals.ula_prefix
set network.globals.packet_steering='1'
set network.lan.gateway='192.168.177.1'
set network.lan.dns='127.0.0.1'
set network.lan6=interface
set network.lan6.proto='dhcpv6'
set network.lan6.device='@lan'
set network.lan6.reqaddress='try'
set network.lan6.reqprefix='auto'
set network.lan6.dns='::1'
EOF
uci commit network
/etc/init.d/network restart

exit 0
